# Generated by Django 5.1.1 on 2024-09-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=15)),
                ('data_nascimento', models.DateField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='capas')),
            ],
        ),
    ]
